watch_interval_sec: 1
aod_output_dir: /var/log/aod

anomalies:
  smb:
    latency:
      tool: "smbslower"
      mode: "all"              # Options: all, trackonly, excludeonly
      acceptable_count: 10     # number of commands with latency above threshold in X seconds
      default_threshold_ms: 20 # milliseconds, by default applies to all commands
      track_commands:
        - command: SMB2_WRITE
          threshold: 0
      actions: [dmesg, journalctl, debugdata, stats, mounts, smbinfo, syslogs]

  nfs:
    latency:
      tool: "nfsslower"
      mode: "all"              # Options: all, trackonly, excludeonly
      acceptable_count: 10     # number of commands with latency above threshold in X seconds
      default_threshold_ms: 0 # milliseconds, by default applies to all commands
      actions: [dmesg, journalctl, syslogs]

cleanup:
  cleanup_interval_sec: 60     # Interval in seconds to run cleanup
  max_log_age_days: 2          # Maximum age of logs in days
  max_total_log_size_mb: 0.5   # Maximum total size of all logs in MB

audit:
  enabled: true

# ** Use either track_commands (trackonly) or exclude_commands (excludeonly).
# Mode type will determine which one is used.
# With Mode type all, track commands with the given thresholds,
# track other commands with the default threshold, and ignore the excluded commands.