"""Generate src/utils/_deps.py from pyproject.toml.

Invoked by the top-level Makefile before packaging.

Emits:
  - REQUIRED     : list of (dist_name, version_spec) from [project.dependencies].
                   Only the simple `name<op>version` form of PEP 508 is handled.
  - MIN_PYTHON   : (major, minor) tuple parsed from `requires-python = ">=X.Y"`.
"""

import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PYPROJECT = REPO_ROOT / "pyproject.toml"
OUT = REPO_ROOT / "src" / "utils" / "_deps.py"

HEADER = (
    "# AUTO-GENERATED by tools/gen_deps.py from pyproject.toml.\n"
    "# Do not edit by hand -- run `make deps` (or any `make rpm`/`make deb`).\n"
    "\n"
)


def _split(spec: str) -> tuple[str, str]:
    """Split e.g. 'numpy>=1.21.0' into ('numpy', '>=1.21.0')."""
    for i, ch in enumerate(spec):
        if ch in "<>=!~":
            return spec[:i].strip(), spec[i:].strip()
    return spec.strip(), ""


def _parse_min_python(req: str) -> tuple[int, int]:
    """Parse `requires-python` like '>=3.11' into (3, 11). Falls back to
    (3, 11) for anything we don't understand."""
    s = req.strip()
    if s.startswith(">="):
        s = s[2:].strip()
    parts = s.split(".")
    try:
        return int(parts[0]), int(parts[1]) if len(parts) > 1 else 0
    except ValueError:
        return (3, 11)


def main() -> None:
    data = tomllib.loads(PYPROJECT.read_text())
    project = data.get("project", {})
    deps = project.get("dependencies", [])
    req_py = project.get("requires-python", ">=3.11")

    entries = [_split(d) for d in deps]
    min_py = _parse_min_python(req_py)

    body = [
        f"MIN_PYTHON: tuple[int, int] = {min_py!r}\n",
        "",
        "REQUIRED: list[tuple[str, str]] = [",
        *[f"    ({n!r}, {v!r})," for n, v in entries],
        "]\n",
    ]
    OUT.write_text(HEADER + "\n".join(body))
    print(
        f"gen_deps: wrote {OUT.relative_to(REPO_ROOT)} "
        f"({len(entries)} deps, min_python={min_py})",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
